export const fitnessClasses = [
  {
    id: 1,
    title: "HIIT Training",
    description: "High-intensity interval training to boost your metabolism.",
    image: "https://media.istockphoto.com/id/1449353914/es/foto/fitness-gimnasio-y-hombre-negro-haciendo-un-entrenamiento-con-pesas-para-la-fuerza-el.jpg?s=612x612&w=0&k=20&c=lLVfK623js8dIA8Gm1Qr-os7TgpbHWbrSfjC2pwcb6Y=",
    duration: "45 min",
    capacity: "12 people",
    instructor: "Sarah Johnson",
  },
  {
    id: 2,
    title: "Yoga Flow",
    description: "Gentle flowing movements to improve flexibility and reduce stress.",
    image: "https://media.istockphoto.com/id/1449353914/es/foto/fitness-gimnasio-y-hombre-negro-haciendo-un-entrenamiento-con-pesas-para-la-fuerza-el.jpg?s=612x612&w=0&k=20&c=lLVfK623js8dIA8Gm1Qr-os7TgpbHWbrSfjC2pwcb6Y=",
    duration: "60 min",
    capacity: "15 people",
    instructor: "Maria Garcia",
  },
  {
    id: 3,
    title: "Strength Training",
    description: "Build muscle and increase strength with our comprehensive weight training program.",
    image: "https://media.istockphoto.com/id/1449353914/es/foto/fitness-gimnasio-y-hombre-negro-haciendo-un-entrenamiento-con-pesas-para-la-fuerza-el.jpg?s=612x612&w=0&k=20&c=lLVfK623js8dIA8Gm1Qr-os7TgpbHWbrSfjC2pwcb6Y=",
    duration: "50 min",
    capacity: "8 people",
    instructor: "Mike Thompson",
  },
  {
    id: 4,
    title: "Pilates Core",
    description: "Strengthen your core and improve posture with targeted Pilates exercises.",
    image: "https://media.istockphoto.com/id/1449353914/es/foto/fitness-gimnasio-y-hombre-negro-haciendo-un-entrenamiento-con-pesas-para-la-fuerza-el.jpg?s=612x612&w=0&k=20&c=lLVfK623js8dIA8Gm1Qr-os7TgpbHWbrSfjC2pwcb6Y=",
    duration: "45 min",
    capacity: "10 people",
    instructor: "Emma Wilson",
  },
  {
    id: 5,
    title: "Cardio Dance",
    description: "Fun and energetic dance workout that combines cardio with rhythm.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVgQZ7W4xoBKpwycIXi1bPmBS0VAtQ8U_Q36U-OsV0R18pHfYtsvUUgTxJOyUEw6AxWco&usqp=CAU",
    duration: "55 min",
    capacity: "20 people",
    instructor: "Lisa Rodriguez",
  },
  {
    id: 6,
    title: "CrossFit",
    description: "Intense functional fitness training for maximum results and endurance.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVgQZ7W4xoBKpwycIXi1bPmBS0VAtQ8U_Q36U-OsV0R18pHfYtsvUUgTxJOyUEw6AxWco&usqp=CAU",
    duration: "60 min",
    capacity: "12 people",
    instructor: "David Chen",
  },
  {
    id: 7,
    title: "Spin Class",
    description: "High-energy indoor cycling class with motivating music and coaching.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVgQZ7W4xoBKpwycIXi1bPmBS0VAtQ8U_Q36U-OsV0R18pHfYtsvUUgTxJOyUEw6AxWco&usqp=CAU",
    duration: "45 min",
    capacity: "16 people",
    instructor: "Alex Turner",
  },
  {
    id: 8,
    title: "Boxing Fitness",
    description: "Learn boxing techniques while getting an incredible full-body workout.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVgQZ7W4xoBKpwycIXi1bPmBS0VAtQ8U_Q36U-OsV0R18pHfYtsvUUgTxJOyUEw6AxWco&usqp=CAU",
    duration: "50 min",
    capacity: "14 people",
    instructor: "Jordan Smith",
  },
  {
    id: 9,
    title: "Aqua Aerobics",
    description: "Low-impact water-based exercise perfect for all fitness levels.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVgQZ7W4xoBKpwycIXi1bPmBS0VAtQ8U_Q36U-OsV0R18pHfYtsvUUgTxJOyUEw6AxWco&usqp=CAU",
    duration: "40 min",
    capacity: "18 people",
    instructor: "Rachel Green",
  },
  {
    id: 10,
    title: "Meditation & Mindfulness",
    description: "Relax and center yourself with guided meditation and breathing exercises.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVgQZ7W4xoBKpwycIXi1bPmBS0VAtQ8U_Q36U-OsV0R18pHfYtsvUUgTxJOyUEw6AxWco&usqp=CAU",
    duration: "30 min",
    capacity: "25 people",
    instructor: "Zen Master Kim",
  },
];